var express = require('express');
var router = express.Router();

const nameList = [
  { 'id': 1, 'Term': 'DevOps', 'Description': "DevOps makes it possible for formerly separate tasks like development, IT operations, quality engineering, and security to coordinate and collaborate. It unifies people, process, and technology in application design, development, delivery, and operations by combining development (Dev) and operations (Ops)", 'References': "mijacobs (2023). What is DevOps? - Azure DevOps. [online] learn.microsoft.com. Available at: https://learn.microsoft.com/en-us/devops/what-is-devops" },
  {'id': 2, 'Term': 'Agile', 'Description': 'Agile is a project management methodology that emphasises incremental and iterative project completion phases. Instead of top-down administration and adhering to a predetermined plan, the strategy places a higher priority on speedy delivery, flexibility, and cooperation.', 'References': 'Coursera. (2023). What Is Agile? And When to Use It. [online] Available at: https://www.coursera.org/articles/what-is-agile-a-beginners-guide' },
  {'id': 3, 'Term': 'Cloud Computing', 'Description': 'The term "cloud computing" refers to an abstraction of the network, storage, and compute resources that have been put together as a platform for the deployment and scalability of software and hardware. Most cloud users use public cloud services over the internet, which are hosted in distant data centres that are managed by cloud  providers.', 'References': 'Knorr, E. (2018). What is cloud computing? Everything you need to know now. [online] InfoWorld. Available at: https://www.infoworld.com/article/2683784/what-is-cloud-computing.html'},
  {'id': 4, 'Term': 'Microservices', 'Description': 'One of the key components of cloud-native computing are microservices. It splits large applications into smaller, loosely linked pieces, facilitating the development of flexible and robust software by developers. Additionally, the shorter development cycles that microservices enable speed up innovation and improve user experience.', 'References': 'Chris Tozzi (2022). An intro to cloud-native microservices and how to build them | TechTarget. [online] Available at: https://www.techtarget.com/searchapparchitecture/tip/An-intro-to-cloud-native-microservices-and-how-to-build-them'},
  {'id': 5, 'Term': 'Monolith Architecture', 'Description': 'In a monolithic architecture, the operating system kernel is created to offer all operating system functions in a single, massive binary, including memory management, process scheduling, device drivers, and file systems. As a result, all code executes in kernel space, with no distinction between kernel-level and user-level processes.', 'References': 'GeeksforGeeks. (2020). Monolithic Architecture. [online] Available at: https://www.geeksforgeeks.org/monolithic-architecture/'},
  {'id': 6, 'Term': 'Orchestration', 'Description': 'In a centralised approach known as orchestration, a central component known as the orchestrator is in charge of overseeing and directing interactions amongst microservices. Examples of orchestration tools are Kubernetes and Docker Swarm.', 'References': 'Kanjilal, J. (2023). Orchestration and choreography in .NET microservices. [online] InfoWorld. Available at: https://www.infoworld.com/article/3687638/orchestration-and-choreography-in-net-microservices.html#:~:text=Microservices%20orchestration%20refers%20to%20a'},
  {'id': 7, 'Term': 'Automation', 'Description': 'IT departments and developers can automatically set up, change, and remove cloud resources thanks to cloud automation. Cloud automation is not a feature of the cloud; rather, it requires knowledge and the usage of specialised tools. Some automation tools include, puppet, ansible, kubernetes, AWS cloud formation, and so on.', 'References': 'Perry, Y. (2019). Cloud Automation: Why, Where and How. [online] bluexp.netapp.com. Available at: https://bluexp.netapp.com/blog/cloud-automation-why-where-and-how-cvo-blg#H4_4'},
  {'id': 8, 'Term': 'Docker', 'Description': 'A software platform called Docker makes it simple to develop, test, and deploy applications. Software is packaged by Docker into standardised units called containers that contain all of the necessary code, libraries, system tools, and runtime.', 'References': 'Amazon Web Services, Inc. (n.d.). What is Docker? | AWS. [online] Available at: https://aws.amazon.com/docker/#:~:text=Docker%20is%20a%20software%20platform'},
  {'id': 9, 'Term': 'Kubernetes', 'Description': 'A portable, adaptable, open-source platform called Kubernetes allows for declarative setup and automation of containerized workloads and services. You can use Kubernetes for things like storage orchestration, service discovery and load balancing.', 'References': 'Kubernetes. (2023). Overview. [online] Available at: https://kubernetes.io/docs/concepts/overview/'},
  {'id': 10, 'Term': 'Terraform', 'Description': 'In order to automate numerous infrastructure activities, DevOps teams frequently employ Terraform, an infrastructure as code tool. One of Terraforms primary use cases is the provisioning of cloud resources. It is an open-source provisioning tool written in the Go language.', 'References': 'Harrington, D. (2023). What is Terraform: Everything You Need to Know | Varonis. [online] www.varonis.com. Available at: https://www.varonis.com/blog/what-is-terraform'}
]

/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'Kachis SIT722 Glossary', sub: 'ABC', names: nameList });
});


module.exports = router;
